LocalTaste/LocalTaste.Mvc/Models/SearchViewModel.cs
using LocalTaste.Domain.POCO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LocalTaste.Mvc.Models
{
    public class SearchViewModel
    {
        public SearchViewModel()
        {
            Results = new List<Restaurant>();
        }

        public string SearchInput { get; set; }
        public IEnumerable<Restaurant> Results { get; set; }
    }
}

LocalTaste/LocalTaste.Mvc/Controllers/RestaurantController.cs
using LocalTaste.Business.Managers.Interfaces;
using LocalTaste.Domain.POCO;
﻿using LocalTaste.Mvc.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LocalTaste.Mvc.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly IRestaurantManager restaurantManager;

        public RestaurantController(IRestaurantManager restMgr)
        {
            this.restaurantManager = restMgr;
        }

        // GET: Restaurant
        public ActionResult Index()
        {
            var restaurants = restaurantManager.Get();
            return View(restaurants);
        }

        // GET: Restaurant/Details/5
        public ActionResult Details(int id)
        {
            var restuarant = restaurantManager.Get(id);
            return View(restuarant);
        }

        // GET: Restaurant/Create
        public ActionResult Create()
        {
            var rest = new Restaurant();
            return View(rest);
        }

        // POST: Restaurant/Create
        [HttpPost]
        public ActionResult Create(Restaurant restaurant)
        {
            try
            {
                restaurantManager.Add(restaurant);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Restaurant/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Restaurant/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Restaurant/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Restaurant/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GET
        public ActionResult Search()
        {
            SearchViewModel vm = new SearchViewModel();
            vm.Results = restaurantManager.Get();
            return View(vm);
        }

        [HttpPost]
        public ActionResult Search(SearchViewModel input)
        {
            input.Results = restaurantManager.Search(input.SearchInput);
            return View(input);

        }
    }
}

LocalTaste/LocalTaste.Mvc/Views/Restaurant/Create.cshtml
@model LocalTaste.Domain.POCO.Restaurant
@{
    ViewBag.Title = "Create";
}

<header>


    <div class="page-title">
        <h2>Local Taste</h2>
        <div class="page-meta">Welcome to Local Taste</div>
    </div>

</header>

<!-- Main Content starts -->
<!-- For sheets effect -->
<div class="main-sheet1"></div>
<div class="main-sheet2"></div>
<div class="main-sheet3"></div>

<div class="main">
    <div class="container">
        <div class="row">
            @using (Html.BeginForm("Create", "Restaurant"))
            {
                @Html.LabelFor(m => m.Name)
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control" })
                
                @Html.LabelFor(m => m.PhoneNumber)
                @Html.TextBoxFor(m => m.PhoneNumber, new { @class = "form-control" })
                
                @Html.LabelFor(m => m.Address.City)
                @Html.TextBoxFor(m => m.Address.City, new { @class = "form-control" })

                @Html.LabelFor(m => m.Address.State)
                @Html.TextBoxFor(m => m.Address.State, new { @class = "form-control" })

                @Html.LabelFor(m => m.Address.Street)
                @Html.TextBoxFor(m => m.Address.Street, new { @class = "form-control" })

                @Html.LabelFor(m => m.Address.Zip)
                @Html.TextBoxFor(m => m.Address.Zip, new { @class = "form-control" })

             <button type="submit"> Submit </button>
            }


        </div>
    </div>
</div>

<!-- Main content ends -->

LocalTaste/LocalTaste.Mvc/Views/Restaurant/Details.cshtml
@model LocalTaste.Domain.POCO.Restaurant
@{
    ViewBag.Title = "Details";
}

<header>

    <div class="page-title">
        <h2>Local Taste</h2>
        <div class="page-meta">Welcome to your restuarant home page</div>
    </div>

</header>

<!-- Main Content starts -->
<!-- For sheets effect -->
<div class="main-sheet1"></div>
<div class="main-sheet2"></div>
<div class="main-sheet3"></div>

<div class="main">
    <div class="container">
        <div class="row">
            <h3>@Model.Name</h3>
            <hr />
            <div class="col-md-12 col-sm-12">

                <!-- About -->
                <div class="rblock">
                    <div class="row">
                        <div class="col-md-3 col-sm-3">
                            <h4>Basic Info</h4>
                        </div>
                        <div class="col-md-9 col-sm-9">
                            <div class="rinfo">
                                <h5>Phone Number</h5>
                                <div class="rmeta">@Model.PhoneNumber</div>
                            </div>
                            <div class="rinfo">
                                <h5>Address</h5>
                                <div class="rmeta">@Model.Address.Street @Model.Address.City @Model.Address.State @Model.Address.Zip </div>
                            </div>
                            <div class="rinfo">
                                <h5>Hourse</h5>
                                <div class="rmeta">Open: @Model.OpenTime Close: @Model.CloseTime </div>
                            </div>
                        </div>
                    </div>
                </div>

                <hr />
                <h4>Reviews</h4>
                <div class="col-md-8 col-sm-8">
                    <div class="posts">
                        @foreach (var review in Model.Reviews)
                        {
                            <div class="entry">
                                <!-- Meta details -->
                                <div class="meta">
                                    <i class="icon-calendar"></i> 26-2-2012 <i class="icon-user"></i> Admin 
                                </div>

                                <p>@review.Message</p>
                                <div class="clearfix"></div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

LocalTaste/LocalTaste.Mvc/Views/Restaurant/Index.cshtml
@model IEnumerable<LocalTaste.Domain.POCO.Restaurant>

@{
    ViewBag.Title = "Index";
}

<header>

    <div class="page-title">
        <h2>Restaurants</h2>
    </div>

</header>

<!-- Main Content starts -->
<!-- For sheets effect -->
<div class="main-sheet1"></div>
<div class="main-sheet2"></div>
<div class="main-sheet3"></div>

<div class="main">
    <div class="container">
        <div class="row">
            <table class="table">
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PhoneNumber)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.WebsiteUrl)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.OpenTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.CloseTime)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.PriceRating)
                    </th>
                    <th></th>
                </tr>

                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PhoneNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.WebsiteUrl)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.OpenTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.CloseTime)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.PriceRating)
                        </td>
                        <td>
                            @Html.ActionLink("Details", "Details", new { id = item.Id }) 
                        </td>
                    </tr>
                }

            </table>
        </div>
    </div>
</div>

LocalTaste/LocalTaste.Mvc/Views/Restaurant/Search.cshtml
@model LocalTaste.Mvc.Models.SearchViewModel
@{
    ViewBag.Title = "Search";
}

<header>

    <div class="page-title">
        <h2>Search</h2>
        <div class="page-meta">This is where you look up your favorite restaurant.</div>
    </div>

</header>

<!-- Main Content starts -->
<!-- For sheets effect -->
<div class="main-sheet1"></div>
<div class="main-sheet2"></div>
<div class="main-sheet3"></div>

<div class="main">
    <div class="container">
        <div class="row">
            @using (Html.BeginForm())
            {
                @Html.TextBoxFor(m => m.SearchInput)
                <button type="submit">Search</button>
            }

            @foreach(var restaurant in Model.Results)
            {
                @Html.DisplayFor(m => restaurant.Name)
            }

        </div>
    </div>
</div>

<!-- Main content ends -->